networks:
  redis-net:      # 定义一个网络名称
    driver: bridge  # 指定了网络的驱动类型，容器连接到 bridge 网络时，它们通过一个私有的虚拟桥接网络来通信，通常用于同一主机上的容器之间的通信
    ipam:   # 控制网络的 IP 地址分配
      driver: default   # 使用了 default 驱动，这意味着 Docker 将使用默认的 IPAM 配置方式来管理 IP 地址
      config:
        - subnet: 172.30.1.0/24 # 定义了一个子网（subnet）

services:
  redis-0:
    image: redis:latest
    container_name: redis-0
    ports:
      - "6379:6379"
    volumes:
      - ./redis-0/data:/data
      - ./redis-0/master-slave-config:/usr/local/etc/redis/
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.2
  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6380:6379"
    volumes:
      - ./redis-1/data:/data
      - ./redis-1/master-slave-config:/usr/local/etc/redis/
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.3
  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6381:6379"
    volumes:
      - ./redis-2/data:/data
      - ./redis-2/master-slave-config:/usr/local/etc/redis/
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.4
  sentinel-1:
    depends_on:
      - redis-0
    image: redis:latest
    container_name: sentinel-1
    ports:
      - "26379:26379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./sentinel1/master-slave-config:/usr/local/etc/redis/
      - ./sentinel1/data:/data
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.5
  sentinel-2:
    depends_on:
      - redis-0
    image: redis:latest
    container_name: sentinel-2
    ports:
      - "26380:26379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./sentinel2/master-slave-config:/usr/local/etc/redis/
      - ./sentinel2/data:/data
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.6
  sentinel-3:
    depends_on:
      - redis-0
    image: redis:latest
    container_name: sentinel-3
    ports:
      - "26381:26379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./sentinel3/master-slave-config:/usr/local/etc/redis/
      - ./sentinel3/data:/data
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.30.1.7