#consumer-application:
#  spring:
#    cloud:
#      loadbalancer:
#        rule: org.springframework.cloud.loadbalancer.core.RandomLoadBalancer

feign:
  httpclient:
    enabled: true
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径最大连接数
#  client:
#    config:
#      default:
#        logger-level: headers

logging:
  level:
    com.example: debug