services:
  mysql_1:
    image: mysql:8.0
    container_name: mysql_1
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/logs:/var/log/mysql
    ports:
      - "3306:3306"

  mysql_2:
    image: mysql:8.0
    container_name: mysql_2
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: slave
      MYSQL_PASSWORD: 123456
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - ./slave/data:/var/lib/mysql
      - ./slave/logs:/var/log/mysql
    ports:
      - "3307:3306"

