services:
  zookeeper1:
    image: zookeeper:3.9.3
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Shanghai
    volumes:
      - ./zookeeper1/data:/data
      - ./zookeeper1/datalog:/datalog
    networks:
      - kafka-net

  zookeeper2:
    image: zookeeper:3.9.3
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Shanghai
    volumes:
      - ./zookeeper2/data:/data
      - ./zookeeper2/datalog:/datalog
    networks:
      - kafka-net

  zookeeper3:
    image: zookeeper:3.9.3
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Shanghai
    volumes:
      - ./zookeeper3/data:/data
      - ./zookeeper3/datalog:/datalog
    networks:
      - kafka-net

  # Kafka 集群配置
  kafka1:
    image: bitnami/kafka:3.9.0
    container_name: kafka1
    hostname: kafka1
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT    # 通信协议
      - KAFKA_LISTENER_PORT=9093    # 端口
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9093   # Kafka广播地址
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093    # Kafka监听地址
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=1   # Kafka节点ID
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 # zookeeper集群地址
      - TZ=Asia/Shanghai
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx2g # 设置最小和最大内存
    ports:
      - "9093:9093"
    volumes:
      - ./kafka_data1:/bitnami/kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: bitnami/kafka:3.9.0
    container_name: kafka2
    hostname: kafka2
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      - TZ=Asia/Shanghai
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx2g # 设置最小和最大内存
    ports:
      - "9094:9094"
    volumes:
      - ./kafka_data2:/bitnami/kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    image: bitnami/kafka:3.9.0
    container_name: kafka3
    hostname: kafka3
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9095
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9095
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9095
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      - TZ=Asia/Shanghai
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx2g # 设置最小和最大内存
    ports:
      - "9095:9095"
    volumes:
      - ./kafka_data3:/bitnami/kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

networks:
  kafka-net:
    driver: bridge