server:
  port: 8006

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.222:8848
    gateway:
      globalcors:     # 跨域处理
        add-to-simple-url-handler-mapping: true  # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':    # 拦截所有请求
            allowed-origin-patterns:  # 允许哪些网站的跨域请求
              - "http://localhost:8001"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers:  #允许在请求中携带的头信息
              - "*"
            allow-credentials: true # 允许携带cookie
            max-age: 360000     # 这次跨域检测的有效期
      routes:
        - id: producer-application  # 唯一id
          uri: lb://producer-application # 路由目标地址
          predicates:
            - Path=/produce/**    # 路径断言，判断路径是否是以/user 开头，如果是则符合，转发至此
          filters:
            - StripPrefix=1
        - id: consumer-application
          uri: lb://consumer-application
          predicates:  ## 断言工厂   https://docs.spring.io/spring-cloud-gateway/docs/4.0.6/reference/html/#gateway-request-predicates-factories
            - Path=/consume/**
#            - RemoteAddr= 192.168.1.1/24  # 限制ip
          filters:
            - StripPrefix=1
      default-filters:
        - AddRequestHeader=X-Request-red, blue  #全局默认过滤器
